[package]
name = "static-dt-rs"
version = "0.1.1"
authors = ["Atmelfan <gustavp@gpa-robotics.com>"]
edition = "2018"
repository = "https://github.com/Atmelfan/static-dt-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]